# Generated by Django 5.1.3 on 2024-12-26 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highscore',
            old_name='name',
            new_name='nickname',
        ),
        migrations.AddField(
            model_name='highscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='highscore',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
